name: chat_app

version: 1.0.0+1

publish_to: none

description: A Flutter chat application

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  sqflite: ^2.3.2
  supabase_flutter: ^2.3.4
  flutter:
    sdk: flutter
  build_runner: ^2.4.8
  json_annotation: ^4.8.1

dev_dependencies:

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  json_serializable: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
