name: chat_app

version: 1.0.0+1

publish_to: none

description: A Flutter chat application

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  sqflite: ^2.3.2
  supabase_flutter: ^2.3.4
  flutter:
    sdk: flutter
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  path: ^1.8.3
  bloc: ^8.1.3
  meta: ^1.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  collection: ^1.18.0
  dynamic_tabbar: ^1.0.7
  grouped_list: ^5.1.2

dev_dependencies:

  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0
  json_serializable: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
